inc:
  # Blog Information
  title:        "Ebola Ghana Alert"
  subtitle:     "Type *713*444# on MTN and Airtel for updates on Ebola"
  cover_image:  blog-cover.jpg
  logo:         logo.png

  # Company information
  company:      Ebola Ghana Alert
  url:          http://app.ebolaghanaalert.org/
  facebook:     ebolaghanaalert
  twitter:      ebolaghanaalert
  gplus:        #'101183822199340201470'

  # Comments
  disqus:
    # Eg. "exampleblog" Set to false to disable comments
    shortname:  false

  # Sharing settings
  sharing:
    twitter:    false
    facebook:   false
    gplus:      false
    hn:         false

 # Analytics
  analytics:
    google: false # Add tracking code in _includes/_google-analytics.html

  # Google Fonts
  google_font: 'Droid+Sans:400,700'

# Show future posts
future:               false
show_drafts:          nil
limit_posts:          0
highlighter:          pygments
relative_permalinks:  true
permalink:            pretty
paginate_path:        'page:num'
paginate:             10
markdown:             redcarpet
excerpt_separator:    "<!-- more -->"
lsi:                  false
baseurl:

sass:
  sass_dir: css/_sass
  style: :compressed

redcarpet:
  extensions: []
